Agregar Código Básico
IIKUYY/CSS pull request #1
Opened 2023-08-23 16:58 UTC by IIKUYY

2023-08-23 17:04 UTC, semanticmx commented
Para todos los repos, desde el inicio hay que agregar el archivo del PR template

2023-08-23 21:38 UTC, semanticmx commented
Si accedes a https://semantic.mx y desactivas los estilos de la página vas a ver algo como esto:
<img width="1405" alt="Screen Shot 2023-08-23 at 11 16 07" src="https://github.com/IIKUYY/CSS/assets/2141584/bfcc00df-8c0f-4468-8f8f-1a48cc999623">

La idea de una implementación semántica de HTML es que puedas navegar el sitio aunque no haya ningún estilo, por ejemplo:

1. En lugar de una barra de navegación se ve un listado de links a los que les puedes dar click
2. El nombre del sitio se destaca como headings de diferentes tamaños
3. Cada sección tiene su heading, textos y formatos de contenido

La versión de Almex es similar, solo que no veo el nombre de Almex, en la versión de Semantic Weapons con estilos se ve una imagen y sin estilos se ve el nombre del sitio.

En general títulos y contenido de las secciones se tienen que implementar con las etiquetas HTML que corresponda.

Como regla general el uso de <div> <span> debe ser limitado al igual que anidar más de 3 niveles las etiquetas.

2023-08-23 21:52 UTC, semanticmx requested changes
hay que aplicar los comentarios a todo el código que aplique por favor.

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +        charset="UTF-8" />
cuando haya un solo atributo el atributo va en la misma línea.

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +        id="contacto">
hay que evitar el uso de ID, en su lugar podemos usar CLASS o DATA-*

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +        <div
Estos divs hay que reemplazarlos por etiquetas semánticas.

En lugar de:

```html
<div 
            id="contactoSucursal">
          <a 
            href="">
            ubica tu sucursal más cercana
          </a>
        </div>
        <div 
            id="formasContacto">
          <a 
            href="">
            comunícate con nosotros
          </a>
        </div>
```

Se puede usar:

```html
<body>
    <header>
      <section> 
        <nav>
          <li>
            <a>Menu Item</a>
          </li>
          <li>
            <a>Menu Item</a>
          </li>
        </nav>
      <section> 
    <header>
```

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +              src="C:\Users\elier\OneDrive\Documentos\GitHub\CSS\template\image 2.png"
Este src no se va a cargar desde internet, implica que tengo que tener Windows, entrar a mi unidad C: y tener una carpeta con esa exacta ruta.

Lo que se tiene que hacer es usar [rutas relativas](https://www.w3schools.com/html/html_filepaths.asp).

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +                <div
hay que revisar el uso de divs anidados, un div semanticamente no significa nada y la mayoría de las veces se puede reemplazar por una etiqueta que le de más significado al contenido:

```html
<nav>
      <ul>
          <li>
            <label>Envios</label>
            <ul>
              <li>Opcion 1</li>
              <li>Opcion 2</li>
            </ul>
          </li>
          <li>
            <label>Soluciones</label>
            <ul>
              <li>Opcion 1</li>
              <li>Opcion 2</li>
            </ul>
          </li>
      </ul>
```

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +            style="background-image: url(C:\Users\elier\OneDrive\Documentos\GitHub\CSS\template\S_r6t7Ew.png);">
El CSS se puede utilizar desde una hoja de estilo a parte, desde el head con la etiqueta <style> o como atributo con el atributo style.

Lo que queremos es mantener independientes la estructura, el estilo y la funcionalidad.

Entonces no debe haber nada de estilos en el HTML, todos se cargan de una hoja de estilos a parte.

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Igual no debe haber texto suelto, fuera de una etiqueta, en este caso se puede usar la etiqueta <p>

2023-08-23 21:52 UTC, semanticmx commented on template/index.html
> +                href="">
El href nunca se deja vacío, si no tenemos links a donde mandar un hipervínculo usamos el hash (#)

```html
<a href="#">
  Link
</a>
```

2023-08-28 04:10 UTC, IIKUYY commented
Cambios realizados

2023-08-28 14:01 UTC, semanticmx requested changes

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +    <header> <! Encabezado
No soy muy fan de los comentarios en HTML, si te das cuenta con las etiquetas semánticas ahora el código se podría ver así:

```html
<header> <!-- Encabezado -->
```

o lo que es lo mismo:

```html
<header> <!-- Header -->
```

Es decir, la etiqueta semántica ya ayuda a que evitemos esos comentarios. Antes tenían más sentido porque el código que veía algo así:

```html
<div> <!-- Contenedor -->
  <div> <!-- Encabezado -->
    <div> <!-- Navegación -->
      <div> <!-- Menu Item -->
```

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +    <section> <! Sección de bienvenida
El formato para los comentarios es:

```html
<!--
```

Faltan los dos guiones medios.

En este caso puedes dejar el comentario ya que aunque es repetitivo `section` y `sección...` el hecho de que sea la sección de bienvenida le da utilidad así que puede quedar como `<!-- Bienvenida -->`

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +            <iframe src="#" frameborder="3"></iframe>
Los iframes generalmente los utilizamos para embedir código que ya existe en otro sitio y que se despliegue en la página "padre".

En el caso del diseño simplemente es un tipo "[card](https://m3.material.io/components/cards/overview)" que muestra el resumen a dos posts recientes, a los cuales al darle click te lleva al blog del sitio.

Estos pueden quedar como `<section>`s del `<article>`

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +                <section>
Este por otro lado en lugar de section puede ser un `<nav>`

Ya que es una lista de links que al darle click te llevan a página externa

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +                    <P>
todas las etiquetas hay que colocarlas en minúsculas

2023-08-28 14:01 UTC, semanticmx commented on template/index.html
> +                <section>
Todos estos sections serían 4 navs

2023-08-30 02:12 UTC, IIKUYY commented
Cambios realizados

2023-08-30 03:44 UTC, semanticmx requested changes

2023-08-30 03:44 UTC, semanticmx commented on template/index.html
> +    <header> <! Encabezado
@IIKUYY este falto de corregir:

dice:

```html
<! Encabezado
```

Debería decir:

```html
<!-- Encabezado
```

O mejor eliminar el comentario porque es redundante aquí

2023-08-30 03:44 UTC, semanticmx commented on template/index.html
> +          content="width=device-width, initial-scale=1" />
en HTML5 ya le podemos quitar el slash (/) final a las etiquetas vacías

en lugar de:

```
<meta name="viewport" 
           content="width=device-width, initial-scale=1" />
```

queda como:

```
<meta name="viewport" 
           content="width=device-width, initial-scale=1">
```

2023-08-30 03:44 UTC, semanticmx commented on template/index.html
> +                <img src="template\Assets\USF.png"
En HTML los separadores de directorios son con slash (/)

dice:

```
<img src="template\Assets\USF.png"
```

debe decir:

```
<img src="template/Assets/USF.png"
```

2023-08-30 13:28 UTC, IIKUYY commented
Cambios realizados

2023-08-30 14:13 UTC, semanticmx requested changes
Puedes revisar este artículo como guía para el armado del layout

https://www.smashingmagazine.com/2009/08/designing-a-html-5-layout-from-scratch/

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +    <section> <! Información general
te faltó este de aquí

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +    <section> <! Galería
y este

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +                <img src="template\Assets\Carretera_gris.png"
Y etsas rutas también hay que cambiarle la diagonal invertida.

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +                        <g id="Ellipse"
hay que hacer un poco de edición a los ID's al copiar los SVG porque como se pasan con el mismo valor eso no se puede tener en HTML.

Generalmente se pueden eliminar solamente, pero también se pueden editar a algo como `id="Ellipse-Aside-1"` o algo así

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +        <main>
Solo debe existir una etiqueta <main> en la página y generalmente se usa para webapps, en otros casos rara vez la usamos ya que es como un duplicado del <body>.

Generalmente la estructura es:

```html
<body>
 <header>
  <nav></nav>
 </header>
 <aside></aside>
 <section>
  <article>
   <header...
   <footer...
  </article>
 ...
 <article>
   <header...
   <footer...
  </article>
 </section>
 <nav></nav>
</body>
```

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +            <section src="#" frameborder="3"></section>
Los section no llevan el atributo `src`

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +        <article>
Los `article` deben de llevar siempre un heading.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

2023-08-30 14:13 UTC, semanticmx commented on template/index.html
> +                <nav>
El `ul` puede ir dentro de un `nav`pero el `nav`no puede ir dentro de un `ul`.

Normalmente la estructura de los footers actuales es usando el tag `footer` como contenedor de la sección.

Luego varias secciones nav como en el caso header+nav, donde cada nav muestra sus links de navegación y son independientes.

Esto aplica para la parte de mobile/responsive ya que si tu tienes un solo bloque (`<ul>...</ul>`) es más difícil partirlo en columnas a que si desde el principio ya tienes muchos bloques (`<nav></nav><nav></nav><nav></nav>`) que puedes sin problema re-acomodar en columnas.

2023-08-30 14:48 UTC, IIKUYY commented
Cambios realizados

2023-08-30 18:30 UTC, semanticmx requested changes

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +        <p>
El uso de esta `<p>` esta raro, a veces se utiliza para agregar una línea de separación pero sería así:

```html
<p>&nbsp;</p>
```

`<p>` es una etiqueta contenedora de texto y dentro del texto podemos agregar `<strong>`, `<small>`, `<i>`, etc., pero no headings.

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +        <section>
Tienes que

a) Buscar todos los `section` y `article` y verificar que usas un heading
o
b) Checar tu layout para ver si necesitas de un section o de otro tag

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +        <main>
Los tags `<main>` yo no los usaría en esta implementación, si se usan no pueden estar dentro de un section, article o algo así, deben ser los contenedores principales

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +            <h1>
Independientemente del tamaño de las fonts en el diseño puedes usar diferentes tipos de headings, si ya usaste un h1 en secciones arriba, las siguientes secciones pueden usar h2

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +                            <path id="Vector"
Este ID se repite, puedes hacer una búsqueda por `id="` y checar si necesitas ajustar otros

2023-08-30 18:30 UTC, semanticmx commented on template/index.html
> +            <li>
acá falta el `ul`

debe quedar así:

```
<footer>
 <nav>
  <ul>
   <li>
    <a>
...
```

2023-08-30 18:31 UTC, semanticmx commented
@IIKUYY puedes usar validadores, ya sea en tu editor de código o de internet:

https://validator.w3.org

<img width="1075" alt="Screen Shot 2023-08-30 at 12 31 05" src="https://github.com/IIKUYY/CSS/assets/2141584/03124e6d-cff9-4de1-b3f4-b034f88f7a99">

2023-09-01 05:44 UTC, IIKUYY commented
Cambios realizados

2023-09-01 15:02 UTC, semanticmx approved these changes
Hay otros ajustes pero ya los vas a ocupar una vez que inicies con el CSS.

Solo revisa esos comentarios para que los vayas aplicando conforme aplicas CSS a esas secciones.

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +        <address>
Address se utiliza para direcciones tipo calle,número, etc.

No se usa para los links.

Aquí para reducir complejidad puedes optar por:

```html
<header>
 <a>
  Ubica...
 </a>
 ...
</header>
```

o recuerda que para los links siempre usamos <nav> cuando son dos o más, ya que se considera ya navegación del sitio.

```html
<header>
 <nav><!-- links --></nav>
 <section><!-- idioma --></section>
</header>
```

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +            <h2>
igual acá, podemos reducir los contenedores quitando el .h2 y dejando el .img como child del .section

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +        </section>
faltó el link de Mi Almex y el icono de búsqueda

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +            <address>
igual, quitamos el .address y solo queda el .button como child del .section

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +    <section>
toda esta sección quedó muy bien.

solo faltaría ver cómo se agregan los iconos del check de employees  y trailers. pero eso puede quedar en otro PR ya que llegues a aplicar estilo a esa parte.

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +        <aside>
aside es más como para barras de navegación laterales.

este puede ser un tercer .article

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +                    Lore ipsum ..........................
aquí hay unas palabras en negritas, esas si las podemos colocar para usar un .strong

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +    <section>
Yo estructuraría esto de la siguiente forma:

```html
...
<section class="featured"></section>
<section></section> <!-- principal -->
<section class="noticias"></section>
<footer></footer>
```

como lo tienes está así:

```html
...
<section> <!--Bienvenida--></section>
<section></section> <!-- Somos líderes -->
<section></section> <!-- 1951 -->
<section class="noticias"></section>
<footer></footer>
```

yo agruparía somos líderes y lo de 1951 en una sola sección porque si te das cuenta en el diseño el fondo de todo eso es blanco y cambia a gris hasta noticias.

Ahora como visualmente hay dos columnas y luego una, tus .section quedaría así:

```html
...
<section class="featured"></section>
<div class="container"> <!-- principal -->
 <section class="2-cols"> <!-- agrupas las primeras dos columnas -->
  <h2>Somos líderes</h2>
  <p>Since...</p>
  <article>
   </h3>385</h3>
   <p>Office...</p>
  </article>
  <article>
   </h2>01</h2>
   <h3>Empresa...</h3>
   <p>Cepteur...</p>
   ...
  </article>
 </section>
 <section> <!-- slider -->
  <article>
   <h2>01</h2>
   <h3>1951</h3>
   <p>ALMEX ...</p>
   <picture></picture>
   <button>&lt;</button>
   <button>&gt;</button>
  </article>
 </section> <!-- Slider dentro de la sección principal. -->
</div>
<section class="noticias"></section>
<footer></footer>
```

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +        <article class="NoticiasPrincipal">
el nombre de las clases hay que usarlo en kebab-case

```html
<article class="noticias-principales">
```

2023-09-01 15:02 UTC, semanticmx commented on template/index.html
> +        <nav>
aquí como no hay links no va el nav, puede ir en un div contenedor.

2023-09-01 15:02 UTC, merged