feat: Chapter14
IIKUYY/CSS pull request #14
Opened 2024-03-07 21:02 UTC by IIKUYY

## what

- Agregar Resumen de animaciones y transiciones
- Mejorar y agregar ejemplos en vivo
- agregar imagen del ejemplo

## why

- Aprender de animaciones y transiciones en CSS3
- Mejorar visibilidad del repositorio

## references
- https://www.dropbox.com/sh/qnq6shvnsd0r3s5/AACEFtOCMAsZeNC5eptW96RSa?e=4&preview=No.Starch.CSS.2nd.Edition.pdf&dl=0

2024-03-07 21:03 UTC, IIKUYY commented
![image](https://github.com/IIKUYY/CSS/assets/69495712/ff438c47-179e-4e71-bc84-84c908403e79)

2024-03-07 21:46 UTC, semanticmx requested changes

2024-03-07 21:46 UTC, semanticmx commented on Chapter14/src/index.css
> +.father {
Para estos ejemplos podrías grabarlos con LiceCAP?

https://www.cockos.com/licecap/

2024-03-07 22:54 UTC, IIKUYY commented
![Example](https://github.com/IIKUYY/CSS/assets/69495712/c6e11a98-cd16-4836-90d1-9e996d62521c)

2024-03-08 02:56 UTC, semanticmx approved these changes

2024-03-08 02:56 UTC, merged